# Project information
site_name: Core Documentation
site_description: API Documentation & Tutorials for the Core Platform.
site_author: Manticore Games, Inc.
site_url: !ENV [MKDOCS_SITE_URL, "https://development.docs.coregames.com"]

# Repository
# repo_name: ManticoreGamesInc/platform-documentation
repo_url: https://github.com/ManticoreGamesInc/platform-documentation/
edit_uri: edit/development/src

# Copyright
copyright: "&copy; 2021 Manticore Games, Inc. Core&trade; is a trademark of Manticore Games"

# Directory for the documentation pages
docs_dir: src

# If you add or remove a page, you must add it here
nav:
  - Documentation:
      - Home: index.md
      - Getting Started:
          - Install Core: getting_started/installing_core.md
          - Intro to the Editor: getting_started/editor_intro.md
          - Make Your First Game:
              - Start Here: getting_started/start.md
              - Create a Shooter Game: getting_started/my_first_multiplayer_game.md
              - Create an RPG Game: tutorials/first_game_rpg.md
              - Create a Survival Game: tutorials/survival_tutorial.md
          - Publish a Game: getting_started/publishing.md
          - Getting Help in Core: getting_started/core_help.md
          - Core for Game Jams: references/global_game_jam.md
      - Coming from other Platforms:
          - Fortnite Creative: other_platforms/fortnite_creative.md
          - Roblox: other_platforms/roblox.md
          - Unity: other_platforms/unity.md
          - World of Warcraft: other_platforms/world_of_warcraft.md
      - Best Practices:
          - Backing Up Your Projects: getting_started/backups.md
          - Collaboration: references/collaboration.md
          - Creator Analytics: tutorials/creator_analytics.md
          - GitHub and Core: tutorials/github.md
          - Improving Your Game: tutorials/improving_your_game.md
          - Lua Style Guide: tutorials/lua_style_guide.md
      - Perks Program:
          - About the Perks Program: references/perks/program.md
          - Perks Rules: references/perks/rules.md
          - Joining the Perks Program: references/perks/joining.md
          - Implementing Perks: references/perks/implementing.md
          - Implementing Reward Points: references/perks/reward_points.md
      - Tutorials:
          - Abilities: tutorials/ability_tutorial.md
          - AI Activities: tutorials/ai_activity_tutorial.md
          - Chat Hooks: tutorials/chat_tutorial.md
          - Environment Art: tutorials/environment_art.md
          - Modeling Basics: tutorials/modeling_basics.md
          - Persistent Storage: tutorials/persistent_storage_tutorial.md
          - Scene Creation: tutorials/scene_creation.md
          - Scripting:
              - Scripting (Beginner): tutorials/lua_basics_helloworld.md
              - Scripting (Intermediate): tutorials/lua_basics_lightbulb.md
              - Scripting (Advanced): tutorials/lua_basics_manticoin.md
          - Survival Contest Kit: references/survival_kit.md
          - Racing Framework Kit: tutorials/racing_tutorial.md
          - Visual Effects in Core: tutorials/vfx_tutorial.md
          - Weapons: tutorials/weapons_tutorial.md
          - Weapons & Abilities (Advanced): tutorials/abilities_advanced.md
      - Core Editor Manual:
          - AI: references/ai.md
          - Animated Meshes: references/animated_meshes.md
          - Art in Core: references/art.md
          - Audio: references/audio.md
          - Community Content: getting_started/community_content.md
          - Contexts: api/contexts.md
          - Curves: references/curves.md
          - Custom Materials: references/custom_materials.md
          - Custom Properties: references/custom_properties.md
          - Editor Shortcuts: references/editor_keybindings.md
          - Frameworks:
              - Dungeon Framework Reference: references/dungeon_framework.md
          - Game Components: api/components.md
          - IK and Custom Animations: references/ik_anchors.md
          - Interconnected Games: references/interconnected_games.md
          - Leaderboards: references/leaderboards.md
          - Merged Models: references/merged_models.md
          - Modeling Reference: references/modeling.md
          - Networking: references/networking.md
          - Object Generator: references/object_generator.md
          - Offline Storage: references/offline_storage.md
          - Party System: references/party_system.md
          - Performance Panel: getting_started/performance_panel.md
          - Persistent Storage: references/persistent_storage.md
          - Play-Mode Profiler: getting_started/profiler.md
          - Portals: references/portals.md
          - Project Files: getting_started/project_files.md
          - Publishing Checklist: getting_started/publishing_checklist.md
          - Queued Games: references/queues.md
          - Scripting Introduction: tutorials/scripting_intro.md
          - Shared Data Storage: references/shared_storage.md
          - Templates: references/templates.md
          - Terrain: references/terrain.md
          - Triggers: references/triggers.md
          - UI: references/ui.md
          - Vehicles: references/vehicles.md
          - Voice Chat: references/voice_chat.md
          - Weapons: references/weapons.md
  - Core API:
      - API Index: api/index.md
      - Animations & Sockets: api/animations.md
      - Editor Extensions: extensions.md
      - Emotes: api/emotes.md
      - Enums: api/enums.md
      - Key Bindings: api/key_bindings.md
      - Lua Style Guide: tutorials/lua_style_guide.md
      - Types:
          - Ability: api/ability.md
          - AbilityPhaseSettings: api/abilityphasesettings.md
          - AbilityTarget: api/abilitytarget.md
          - AIActivity: api/aiactivity.md
          - AIActivityHandler: api/aiactivityhandler.md
          - AnimatedMesh: api/animatedmesh.md
          - AreaLight: api/arealight.md
          - Audio: api/audio.md
          - Camera: api/camera.md
          - CameraCapture: api/cameracapture.md
          - Color: api/color.md
          - CoreFriendCollection: api/corefriendcollection.md
          - CoreFriendCollectionEntry: api/corefriendcollectionentry.md
          - CoreGameCollectionEntry: api/coregamecollectionentry.md
          - CoreGameInfo: api/coregameinfo.md
          - CoreMesh: api/coremesh.md
          - CoreObject: api/coreobject.md
          - CoreObjectReference: api/coreobjectreference.md
          - CorePlayerProfile: api/coreplayerprofile.md
          - CurveKey: api/curvekey.md
          - CustomMaterial: api/custommaterial.md
          - Damage: api/damage.md
          - Decal: api/decal.md
          - Equipment: api/equipment.md
          - Event: api/event.md
          - EventListener: api/eventlistener.md
          - Folder: api/folder.md
          - FourWheeledVehicle: api/fourwheeledvehicle.md
          - HitResult: api/hitresult.md
          - Hook: api/hook.md
          - HookListener: api/hooklistener.md
          - IKAnchor: api/ikanchor.md
          - ImpactData: api/impactdata.md
          - LeaderboardEntry: api/leaderboardentry.md
          - Light: api/light.md
          - MaterialSlot: api/materialslot.md
          - MergedModel: api/mergedmodel.md
          - NetReference: api/netreference.md
          - NetworkContext: api/networkcontext.md
          - Object: api/object.md
          - Other: api/other.md
          - PartyInfo: api/partyinfo.md
          - PhysicsObject: api/physicsobject.md
          - Player: api/player.md
          - PlayerSettings: api/playersettings.md
          - PlayerStart: api/playerstart.md
          - PlayerTransferData: api/playertransferdata.md
          - PointLight: api/pointlight.md
          - Projectile: api/projectile.md
          - Quaternion: api/quaternion.md
          - RandomStream: api/randomstream.md
          - Rotation: api/rotation.md
          - Script: api/script.md
          - ScriptAsset: api/scriptasset.md
          - SimpleCurve: api/simplecurve.md
          - SmartAudio: api/smartaudio.md
          - SmartObject: api/smartobject.md
          - SpotLight: api/spotlight.md
          - StaticMesh: api/staticmesh.md
          - Task: api/task.md
          - Terrain: api/terrain.md
          - TreadedVehicle: api/treadedvehicle.md
          - Transform: api/transform.md
          - Trigger: api/trigger.md
          - UIButton: api/uibutton.md
          - UIContainer: api/uicontainer.md
          - UIControl: api/uicontrol.md
          - UIImage: api/uiimage.md
          - UIPanel: api/uipanel.md
          - UIPerkPurchaseButton: api/uiperkpurchasebutton.md
          - UIProgressBar: api/uiprogressbar.md
          - UIRewardPointsMeter: api/uirewardpointsmeter.md
          - UIScrollPanel: api/uiscrollpanel.md
          - UIText: api/uitext.md
          - Vector2: api/vector2.md
          - Vector3: api/vector3.md
          - Vector4: api/vector4.md
          - Vehicle: api/vehicle.md
          - Vfx: api/vfx.md
          - Weapon: api/weapon.md
          - WorldText: api/worldtext.md
      - Namespaces:
          - Chat: api/chat.md
          - Core Functions: api/coreluafunctions.md
          - CoreDebug: api/coredebug.md
          - CoreMath: api/coremath.md
          - CorePlatform: api/coreplatform.md
          - CoreSocial: api/coresocial.md
          - CoreString: api/corestring.md
          - Environment: api/environment.md
          - Events: api/events.md
          - Game: api/game.md
          - Input: api/input.md
          - Leaderboards: api/leaderboards.md
          - Storage: api/storage.md
          - Teams: api/teams.md
          - UI: api/ui.md
          - VoiceChat: api/voicechat.md
          - World: api/world.md
  - Core Academy:
      - Academy: https://learn.coregames.com
  - Forums:
      - Forums: https://forums.coregames.com
  - News:
      - News: https://forums.coregames.com/c/community/5
  - Content Creator Kit:
      - Core Content Creator Kit: creator_kit/index.md
  - Feedback:
      - Feedback: https://support.coregames.com/hc/en-us/requests/new

# Theme configuration
theme:
  name: material
  custom_dir: mkdocs-material/material
  language: en
  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.top
  palette:
    primary: core-orange
    accent: core-blue
  logo: assets/icons/favicon-196x196.png
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  static_templates:
    - 404.html
    - offline.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

extra_css:
  - assets/stylesheets/lite-yt-embed.css
  - assets/stylesheets/docsearch.css

extra_javascript:
  - assets/javascripts/manticore.js
  - assets/javascripts/lite-yt-embed.js
  - assets/javascripts/tables.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Français (Beta)
      link: /fr/
      lang: fr
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  feedback_url: https://github.com/ManticoreGamesInc/platform-documentation/issues/new
  generator: false
  robots: !ENV [ROBOTS, "noindex"]
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/core-creators
      name: Discord
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/CoreGamesOfficial
      name: YouTube
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/PlayCoreGames
      name: Reddit
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/playcoregames
      name: Facebook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/coregames
      name: Twitter
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/corelive
      name: Twitch

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys:
      camel_case: true
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ManticoreGamesInc
      repo: platform-documentation
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - full_yaml_metadata
  - lightgallery

plugins:
  - search
  - tags:
      tags_file: generated/tags.md
  - git-revision-date-localized
  - ezlinks
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, true]
      languages:
        fr: Français (Beta)
  - minify:
      minify_html: !ENV MKDOCS_MINIFY
  - redirects:
      redirect_maps:
        perks/implementing_perks.md: references/perks/implementing.md
        perks/joining_perks.md: references/perks/joining.md
        perks/perks_program.md: references/perks/program.md
        perks/perks_rules.md: references/perks/rules.md
        perks/perks.md: references/perks/program.md
        perks/index.md: references/perks/program.md
        reward_points/reward_points_reference.md: references/perks/reward_points.md
        tutorials/ai_reference.md: references/ai.md
        tutorials/animated_mesh.md: references/animated_meshes.md
        tutorials/art_reference.md: references/art.md
        tutorials/audio_reference.md: references/audio.md
        tutorials/collaboration_overview.md: references/collaboration.md
        tutorials/curves.md: references/curves.md
        tutorials/custom_materials.md: references/custom_materials.md
        tutorials/custom_properties.md: references/custom_properties.md
        tutorials/dungeon_framework_reference.md: references/dungeon_framework.md
        editor_keybindings.md: references/editor_keybindings.md
        tutorials/global_game_jam.md: references/global_game_jam.md
        tutorials/ik_anchors.md: references/ik_anchors.md
        tutorials/interconnected_games.md: references/interconnected_games.md
        tutorials/leaderboards.md: references/leaderboards.md
        tutorials/merged_models.md: references/merged_models.md
        tutorials/modeling_reference.md: references/modeling.md
        tutorials/networking.md: references/networking.md
        tutorials/object_generator.md: references/object_generator.md
        tutorials/offline_storage.md: references/offline_storage.md
        tutorials/party_system.md: references/party_system.md
        tutorials/persistent_storage.md: references/persistent_storage.md
        tutorials/portal_reference.md: references/portals.md
        tutorials/queues.md: references/queues.md
        tutorials/shared_storage.md: references/shared_storage.md
        tutorials/survival_kit.md: references/survival_kit.md
        tutorials/template_reference.md: references/templates.md
        tutorials/triggers.md: references/triggers.md
        tutorials/ui_reference.md: references/ui.md
        tutorials/vehicles.md: references/vehicles.md
        tutorials/weapons.md: references/weapons.md
        start.md: getting_started/start.md
        getting_started.md: getting_started/editor_intro.md
        news/showcase/just_getting_started.md: getting_started/editor_intro.md
        showcase/just_getting_started.md: getting_started/editor_intro.md
        tutorials/abilities.md: tutorials/ability_tutorial.md
        getting_started/other_engines.md: other_platforms/unity.md
        getting_started/troubleshooting.md: getting_started/core_help.md
        getting_started/other_platforms.md: other_platforms/unity.md
        tutorials/environmental_art.md: tutorials/environment_art.md
        tutorials/collaboration.md: tutorials/github.md
        api/ability_bindings.md: api/key_bindings.md
        core_api.md: api/index.md
        api/examples.md: api/index.md
        tutorials/videos/pistol_shooter.md: https://www.youtube.com/CoreGamesOfficial
