# Project information
site_name: Core Documentation
site_description: API Documentation & Tutorials for the Core Platform.
site_author: Manticore Games, Inc.
site_url: https://development.docs.coregames.com

# Repository
# repo_name: ManticoreGamesInc/platform-documentation
repo_url: https://github.com/ManticoreGamesInc/platform-documentation/
edit_uri: edit/development/src

# Copyright
copyright: "&copy; 2021 Manticore Games, Inc. Core&trade; is a trademark of Manticore Games"

# Directory for the documentation pages
docs_dir: src

# If you add or remove a page, you must also add or remove in mkdocs-prod.yml
nav:
  - Documentation:
      - Home: index.md
      - Getting Started:
          - Install Core: getting_started/installing_core.md
          - Intro to the Editor: getting_started/editor_intro.md
          - Create your first Game: getting_started/my_first_multiplayer_game.md
          - Create your first RPG game: tutorials/first_game_rpg.md
          - Publish a Game: getting_started/publishing.md
          - Getting Help in Core: getting_started/core_help.md
      - Global Game Jam 2021:
          - Core for Global Game Jam: tutorials/global_game_jam.md
      - Coming from other Platforms:
          - Fortnite Creative: other_platforms/fortnite_creative.md
          - Roblox: other_platforms/roblox.md
          - Unity: other_platforms/unity.md
          - World of Warcraft: other_platforms/world_of_warcraft.md
      - Best Practices:
          - Collaboration: tutorials/collaboration_overview.md
          - Creator Analytics: tutorials/creator_analytics.md
          - GitHub and Core: tutorials/github.md
          - Improving Your Game: tutorials/improving_your_game.md
          - Lua Style Guide: tutorials/lua_style_guide.md
      - Perks Program:
          - About the Perks Program: perks/perks_program.md
          - Perks Rules: perks/perks_rules.md
          - Joining the Perks Program: perks/joining_perks.md
          - Implementing Perks: perks/implementing_perks.md
      - Tutorials:
          - Abilities: tutorials/abilities.md
          - Environment Art: tutorials/environment_art.md
          - Modeling Basics: tutorials/modeling_basics.md
          - Persistent Storage: tutorials/persistent_storage_tutorial.md
          - Scene Creation: tutorials/scene_creation.md
          - Scripting:
              - Scripting (Beginner): tutorials/lua_basics_helloworld.md
              - Scripting (Intermediate): tutorials/lua_basics_lightbulb.md
              - Scripting (Advanced): tutorials/lua_basics_manticoin.md
          - Survival Game:
              - Survival Contest Kit: tutorials/survival_kit.md
              - Survival Tutorial: tutorials/survival_tutorial.md
          - Video Tutorials:
            - Making a Pistol Shooter: tutorials/videos/pistol_shooter.md
          - Visual Effects in Core: tutorials/vfx_tutorial.md
          - Weapons: tutorials/weapons_tutorial.md
          - Weapons & Abilities (Advanced): tutorials/abilities_advanced.md
      - Core Editor Manual:
          - Animated Meshes: tutorials/animated_mesh.md
          - Art in Core: tutorials/art_reference.md
          - Audio: tutorials/audio_reference.md
          - Community Content: getting_started/community_content.md
          - Contexts: api/contexts.md
          - Custom Materials: tutorials/custom_materials.md
          - Editor Shortcuts: editor_keybindings.md
          - Frameworks:
              - Dungeon Framework Reference: tutorials/dungeon_framework_reference.md
          - Game Components: api/components.md
          - Interconnected Games: tutorials/interconnected_games.md
          - Merged Models: tutorials/merged_models.md
          - Modeling Reference: tutorials/modeling_reference.md
          - Networking: tutorials/networking.md
          - Object Generator: tutorials/object_generator.md
          - Performance Panel: getting_started/performance_panel.md
          - Persistent Storage: tutorials/persistent_storage.md
          - Play-Mode Profiler: getting_started/profiler.md
          - Publishing Checklist: getting_started/publishing_checklist.md
          - Scripting Introduction: tutorials/scripting_intro.md
          - Shared Data Storage: tutorials/shared_storage.md
          - Templates: tutorials/template_reference.md
          - UI: tutorials/ui_reference.md
          - Weapons: tutorials/weapons.md
  - Core API:
      - Reference: api/index.md
      - Enums: api/enums.md
      - Animations & Sockets: api/animations.md
      - Editor Extensions: extensions.md
      - Key Bindings: api/key_bindings.md
      - Lua Style Guide: tutorials/lua_style_guide.md
      - Types:
          - Ability: api/ability.md
          - AbilityPhaseSettings: api/abilityphasesettings.md
          - AbilityTarget: api/abilitytarget.md
          - AnimatedMesh: api/animatedmesh.md
          - AreaLight: api/arealight.md
          - Audio: api/audio.md
          - Camera: api/camera.md
          - Color: api/color.md
          - CoreMesh: api/coremesh.md
          - CoreObject: api/coreobject.md
          - CoreObjectReference: api/coreobjectreference.md
          - CoreString: api/corestring.md
          - Damage: api/damage.md
          - Decal: api/decal.md
          - Equipment: api/equipment.md
          - Event: api/event.md
          - EventListener: api/eventlistener.md
          - Folder: api/folder.md
          - HitResult: api/hitresult.md
          - Hook: api/hook.md
          - HookListener: api/hooklistener.md
          - ImpactData: api/impactdata.md
          - LeaderboardEntry: api/leaderboardentry.md
          - Light: api/light.md
          - MergedModel: api/mergedmodel.md
          - NetReference: api/netreference.md
          - NetworkContext: api/networkcontext.md
          - Object: api/object.md
          - Other: api/other.md
          - PhysicsObject: api/physicsobject.md
          - Player: api/player.md
          - PlayerSettings: api/playersettings.md
          - PlayerStart: api/playerstart.md
          - PointLight: api/pointlight.md
          - Projectile: api/projectile.md
          - Quaternion: api/quaternion.md
          - RandomStream: api/randomstream.md
          - Rotation: api/rotation.md
          - Script: api/script.md
          - ScriptAsset: api/scriptasset.md
          - SmartAudio: api/smartaudio.md
          - SmartObject: api/smartobject.md
          - SpotLight: api/spotlight.md
          - StaticMesh: api/staticmesh.md
          - Task: api/task.md
          - Terrain: api/terrain.md
          - Transform: api/transform.md
          - Trigger: api/trigger.md
          - UIButton: api/uibutton.md
          - UIContainer: api/uicontainer.md
          - UIControl: api/uicontrol.md
          - UIImage: api/uiimage.md
          - UIPanel: api/uipanel.md
          - UIPerkPurchaseButton: api/uiperkpurchasebutton.md
          - UIProgressBar: api/uiprogressbar.md
          - UIScrollPanel: api/uiscrollpanel.md
          - UIText: api/uitext.md
          - Vector2: api/vector2.md
          - Vector3: api/vector3.md
          - Vector4: api/vector4.md
          - Vfx: api/vfx.md
          - Weapon: api/weapon.md
          - WorldText: api/worldtext.md
      - Namespaces:
          - Core Functions: api/coreluafunctions.md
          - CoreDebug: api/coredebug.md
          - CoreMath: api/coremath.md
          - Environment: api/environment.md
          - Events: api/events.md
          - Game: api/game.md
          - Leaderboards: api/leaderboards.md
          - Storage: api/storage.md
          - Teams: api/teams.md
          - UI: api/ui.md
          - World: api/world.md

  - Core Academy:
      - Academy: https://learn.coregames.com
  - Forums:
      - Forums: https://forums.coregames.com
  - News:
      - News: https://forums.coregames.com/c/community/5
  - Feedback:
      - Feedback: https://support.coregames.com/hc/en-us/requests/new

# Theme configuration
theme:
  name: null
  custom_dir: mkdocs-material/material
  language: en
  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - toc.integrate
  palette:
    primary: core-orange
    accent: core-blue
  logo: assets/icons/favicon-196x196.png
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  static_templates:
    - 404.html
    - offline.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

extra_css:
  - assets/stylesheets/lite-yt-embed.css
  - assets/stylesheets/algolia.css

extra_javascript:
  - assets/javascripts/manticore.js
  - assets/javascripts/lite-yt-embed.js

extra:
  feedback_url: https://github.com/ManticoreGamesInc/platform-documentation/issues/new
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/core-creators
      name: Discord
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/CoreGamesOfficial
      name: YouTube
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/PlayCoreGames
      name: Reddit
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/playcoregames
      name: Facebook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/coregames
      name: Twitter
    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/corelive
      name: Twitch

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  #- pymdownx.highlight:
  #linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys:
      camel_case: true
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ManticoreGamesInc
      repo: platform-documentation
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - full_yaml_metadata
  - lightgallery

plugins:
  - search
  - tags:
      tags_folder: src/generated
  - git-revision-date-localized
  - autolinks
  - redirects:
      redirect_maps:
        getting_started.md: getting_started/editor_intro.md
        news/showcase/just_getting_started.md: getting_started/editor_intro.md
        showcase/just_getting_started.md: getting_started/editor_intro.md
        tutorials/examples.md: https://docs.coregames.com/api/examples.md
        tutorials/gameplay/abilities.md: tutorials/abilities.md
        tutorials/gameplay/weapons.md: tutorials/weapons.md
        tutorials/gameplay/abilities_advanced.md: tutorials/abilities_advanced.md
        tutorials/gameplay/lua_basics_lightbulb.md: tutorials/lua_basics_lightbulb.md
        tutorials/gameplay/lua_basics_manticoin.md: tutorials/lua_basics_manticoin.md
        tutorials/gameplay/persistent_storage.md: tutorials/persistent_storage.md
        tutorials/art/scene_creation.md: tutorials/scene_creation.md
        tutorials/art/environmental_art.md: tutorials/environment_art.md
        tutorials/art/modeling_basics.md: tutorials/modeling_basics.md
        tutorials/gameplay/lua_style_guide.md: tutorials/lua_style_guide.md
        getting_started/other_engines.md: other_platforms/unity.md
        getting_started/troubleshooting.md: getting_started/core_help.md
        getting_started/other_platforms.md: other_platforms/unity.md
        tutorials/environmental_art.md: tutorials/environment_art.md
        tutorials/collaboration.md: tutorials/github.md
        tutorials/rpg_framework_reference.md: tutorials/dungeon_framework_reference.md
        tutorials/rpg_framework_documentation.md: tutorials/dungeon_framework_reference.md
        tutorials/rpg_framework_overview.md: tutorials/dungeon_framework_reference.md
        tutorials/: tutorials/overview.md
        perks/: perks/perks_program.md
        perks/perks.md: perks/implementing_perks.md
        api/ability_bindings.md: api/key_bindings.md
        core_api.md: api/index.md
        api/examples.md: api/index.md
        tutorials/lua_reference.md: tutorials/scripting_intro.md
